export const DUMMY_DATA = [
    {
        id: 1,
        image: "https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1694712318/Croma%20Assets/Communication/Wearable%20Devices/Images/300676_0_logazn.png?tr=w-400",
        title: "Apple Watch SE Gen 2",
        subtitle: "With solo loop",
        primaryColor: "#FFC8B7",
        category: "Apple",
        colors: [{name: 'Silver', code: 'gray'}, {name: "Bright Orange", code: "orange"}, {name: "Starlight", code: "#808080"}, {name:"Black", code: "black"}, {name: "Red", code: "red"}],
        detail: "All the essentials to help you be motivated and active, keep connected, track your health, and stay safe. The Smart Stack and redesigned apps in watchOS 10 help you see more information at a glance. With features like Crash Detection and enhanced workout metrics, Apple Watch SE is a better value than ever.",
        price: '$349.99',
        star: '4.9',
        review: []
    },
    {
        id: 2,
        image: "https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1691134303/Croma%20Assets/Wearable/Wearable%20Devices/Images/275944_hmcg6b.png?tr=w-400",
        title: "Galaxy Watch 4",
        subtitle: "With solo loop",
        primaryColor: "#FEEFE0",
        category: "Samsung",
        colors: [{name: 'Silver', code: 'gray'}, {name: "Bright Orange", code: "orange"}, {name:"Black", code: "black"}, {name: "Red", code: "red"}],
        detail: "Designed with a generous and vibrant 1.5-inch AMOLED display, the SAMSUNG Galaxy Watch6 Classic Smartwatch offers a convenient and speedy way to check notifications, apps, and other features. What’s more, the combination of a round dial and sleek design imparts a touch of stylish flair and elevates your overall outfit.",
        price: '$249.99',
        star: '4.1',
        review: []
    },
    {
        id: 3,
        title: "Amazfit GTS 2",
        image: "https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1706882831/Croma%20Assets/Communication/Wearable%20Devices/Images/302168_0_rqwajf.png?tr=w-400",
        subtitle: "With solo loop",
        primaryColor: "#FCF1F0",
        category: "Xiaomi",
        colors: [{name: 'Silver', code: 'gray'}, {name: "Blue", code: "blue"}, {name:"Black", code: "black"}, {name: "Red", code: "red"}],
        detail: "Immerse yourself in the vibrant 1.69-inch HD touch display of the amazfit Bip 3 smartwatch. The large and colorful screen enhances visibility, making it easy to navigate through your watch functions, notifications, and more. Enjoy a crystal-clear visual experience on your wrist.",
        price: '$199.99',
        star: '3.7',
        review: []
    },
    {
        id: 4,
        image: "https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1675187472/Croma%20Assets/Communication/Wearable%20Devices/Images/260632_0_gkm677.png?tr=w-400",
        title: "Galaxy Watch 5 Pro",
        subtitle: "With solo loop",
        primaryColor: "#F0DEC5",
        category: "Samsung",
        colors: [{name: 'Silver', code: 'gray'}, {name: "Bright Orange", code: "orange"}, {name: "Starlight", code: "#808080"}, {name:"Black", code: "black"}, {name: "White", code: "white"}, {name: "Red", code: "red"}],
        detail: "Designed with a generous and vibrant 1.5-inch AMOLED display, the SAMSUNG Galaxy Watch6 Classic Smartwatch offers a convenient and speedy way to check notifications, apps, and other features. What’s more, the combination of a round dial and sleek design imparts a touch of stylish flair and elevates your overall outfit.",
        price: '$239.99',
        star: '4.8',
        review: []
    },
    {
        id: 5,
        title: "Apple Watch 8",
        image: "https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1685967383/Croma%20Assets/Communication/Wearable%20Devices/Images/262076_lfbftp.png?tr=w-400",
        subtitle: "With solo loop",
        primaryColor: "#BDBDBD",
        category: "Apple",
        colors: [{name: 'Silver', code: 'gray'}, {name: "Bright Orange", code: "orange"}, {name: "Starlight", code: "#808080"}, {name:"Black", code: "black"}, {name: "Red", code: "red"}],
        detail: "The aluminium case is lightweight and made from 100 percent recycled aerospace grade alloy",
        price: '$449.99',
        star: '5.0',
        review: []
    },
    {
        id: 6,
        title: "Galaxy Watch 5",
        image: "https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1703081985/Croma%20Assets/Communication/Wearable%20Devices/Images/275934_0_phlr5b.png?tr=w-400",
        subtitle: "With solo loop",
        primaryColor: "#A13B3B",
        category: "Samsung",
        colors: [{name: 'Silver', code: 'gray'}, {name: "Starlight", code: "#808080"}, {name:"Black", code: "black"}, {name: "Red", code: "red"}],
        detail: "Designed with a generous and vibrant 1.5-inch AMOLED display, the SAMSUNG Galaxy Watch6 Classic Smartwatch offers a convenient and speedy way to check notifications, apps, and other features. What’s more, the combination of a round dial and sleek design imparts a touch of stylish flair and elevates your overall outfit.",
        price: '$289.99',
        star: '4.1',
        review: []
    },
    {
        id: 7,
        title: "Amazfit Bip 3",
        image: "https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1703235602/Croma%20Assets/Wearable/Wearable%20Devices/Images/257068_oqtbbp.png?tr=w-400",
        subtitle: "With solo loop",
        category: "Xiaomi",
        primaryColor: "#434F9A",
        colors: [{name: 'Silver', code: 'gray'}, {name: "Blue", code: "blue"}, {name:"Black", code: "black"}, {name: "Red", code: "red"}],
        detail: "Immerse yourself in the vibrant 1.69-inch HD touch display of the amazfit Bip 3 smartwatch. The large and colorful screen enhances visibility, making it easy to navigate through your watch functions, notifications, and more. Enjoy a crystal-clear visual experience on your wrist.",
        price: '$217.99',
        star: '4.0',
        review: []
    },
    {
        id: 8,
        title: "Noise Twist Go",
        image: "https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1709018625/Croma%20Assets/Wearable/Wearable%20Devices/Images/305115_zlc7ed.png?tr=w-400",
        subtitle: "With solo loop",
        primaryColor: "#E4E4E4",
        category: "Twist",
        colors: [{name: 'Silver', code: 'gray'}, {name: "Bright Orange", code: "orange"}, {name: "Starlight", code: "#808080"}, {name:"Black", code: "black"}, {name: "White", code: "white"}, {name: "Red", code: "red"}, {name: "Blue", code: "blue"}],
        detail: "Keep in touch effortlessly with Tru Sync-enabled Bluetooth calling and social media notifications on the noise Twist Go smartwatch. This versatile wearable is designed to keep you connected and efficient all day long. Get alerts for calls, messages, and social updates right on your wrist, keeping you informed without needing to reach for your phone.",
        price: '$309.99',
        star: '4.6',
        review: []
    }
]